events/urls.py
from django.urls import path, re_path
from . import views

app_name = 'events'
urlpatterns = [

    re_path(r'^eventos/?$', views.eventos, name='eventos'),
    re_path(r'^eventos/criar/?$', views.criar_evento, name='criar_evento'),

    # Calendar manager
    path('eventos/manager/', views.eventos_manager, name='eventos_manager'),
    path('eventos/e/<int:calendar_id>', views.eventos_edit, name='eventos_edit'),
    path('eventos/d/<int:calendar_id>', views.eventos_delete, name='eventos_delete'),
]

home/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^c/add/?$', views.carrousel_add, name='carrousel_editor'),
    re_path(r'^c/?$', views.carrousel, name='carrousel'),
    re_path(r'^404/?$', views.does_not_exists, name='does_not_exists'),
    path('c/delete/<item_id>', views.carrousel_delete, name='carrousel_delete'),
]

portal_umadjaf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('', include('shop.urls')),
    path('', include('manager.urls')),
    path('', include('articles.urls')),
    path('', include('events.urls')),
    path('', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/models.py
import os
from django.db import models
from manager.models import Congregations


# Upload de imagens para o banner do evento
def get_upload_to_calendar(instance, filename):
    return f'events/{instance.date}/{filename}'


# Modelo de eventos
class Event(models.Model):
    '''
    Modelo de eventos

    Atributos:
        title (str): Título do evento
        date (date): Data do evento
        hours (time): Horário do evento
        theme (str): Tema do evento
        is_general (bool): Se é evento geral
        congregation (int): Congregação do evento
        logo (image): Logo do evento
        background (image): Imagem de fundo do evento
        author_id (int): ID do autor do evento
    '''
    title = models.CharField(max_length=200)
    date = models.DateField()
    hours = models.TimeField()
    theme = models.TextField(default='')
    is_general = models.BooleanField(default=False)
    congregation = models.ForeignKey(Congregations, on_delete=models.CASCADE)
    logo = models.ImageField(
        upload_to=get_upload_to_calendar,
        default='events/default.jpg'
    )
    background = models.ImageField(
        upload_to=get_upload_to_calendar,
        default='events/default.jpg'
    )
    author_id = models.IntegerField(default=0)

    # Deletar imagens do evento ao deletar o evento
    def delete(self, *args, **kwargs):
        directories_to_check = set()

        if self.logo and os.path.isfile(self.logo.path):
            os.remove(self.logo.path)
            directories_to_check.add(os.path.dirname(self.logo.path))

        if self.background and os.path.isfile(self.background.path):
            os.remove(self.background.path)
            directories_to_check.add(os.path.dirname(self.background.path))

        for directory in directories_to_check:
            if not os.listdir(directory):
                os.rmdir(directory)

        super(Event, self).delete(*args, **kwargs)

    def __str__(self):
        return f'{self.title} ({self.date})'

events/forms.py
from django import forms  # type: ignore
from manager.models import Congregations
from .models import Event


# Formulário de calendário
class CalendarForm(forms.ModelForm):
    title = forms.CharField(
        label='Título',
        widget=forms.TextInput(attrs={
            'autocomplete': 'off',
            'id': 'title-calendar',
            'class': 'form-control'  # Adiciona a classe do Bootstrap
        })
    )
    date = forms.DateField(
        label='Data',
        widget=forms.DateInput(attrs={
            'type': 'date',
            'class': 'form-control'  # Adiciona a classe do Bootstrap
        })
    )
    theme = forms.CharField(
        label='Tema',
        widget=forms.TextInput(attrs={
            'autocomplete': 'off',
            'id': 'theme-calendar',
            'class': 'form-control'  # Adiciona a classe do Bootstrap
        })
    )
    is_general = forms.BooleanField(
        label='Geral',
        required=False
    )
    congregation = forms.ModelChoiceField(
        queryset=Congregations.objects.all(),
        empty_label='Selecione uma igreja',
        label='Congregação',
        widget=forms.Select(attrs={
            'class': 'form-select'  # Adiciona a classe do Bootstrap para selects
        })
    )
    logo = forms.ImageField(
        label='Logo',
        widget=forms.FileInput(attrs={
            'class': 'form-control'  # Adiciona a classe do Bootstrap para inputs de arquivo
        })
    )
    background = forms.ImageField(
        label='Background',
        widget=forms.FileInput(attrs={
            'class': 'form-control'  # Adiciona a classe do Bootstrap para inputs de arquivo
        })
    )

    class Meta:
        model = Event
        # Adicione aqui os campos que você deseja editar
        fields = ['title', 'date',
                  'theme', 'is_general', 'congregation', 'logo', 'background']

events/views.py
from django.shortcuts import render, redirect
from utils.decorators import authenticated_user
from django.http import HttpResponseRedirect
from django.utils import timezone
from .forms import CalendarForm
from manager.models import Congregations
from .models import Event


'''
É utilizado o decorator @authenticated_user para verificar se o usuário está
autenticado.

Ele entrega os seguintes parâmetros para as views:
    - is_authenticated: Indica se o usuário está autenticado.
    - is_admin: Indica se o usuário é um administrador.
    - is_media_manager: Indica se o usuário é um gerente de mídia.
    - is_devotion_manager: Indica se o usuário é um gerente de devoções.
    - is_coordinator: Indica se o usuário é um coordenador.
    - is_umadjaf: Indica se o usuário é um membro da UMADJAF.
'''


# Eventos do calendário
@authenticated_user
def eventos(request,
            is_authenticated,
            is_admin,
            is_media_manager,
            is_devotion_manager,
            is_coordinator,
            is_umadjaf
            ):
    '''
    Exibe os eventos futuros no portal UMADJAF.

    Parâmetros:
        - request: A requisição HTTP recebida.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - Um objeto HttpResponse contendo a página HTML renderizada com a lista de eventos futuros.

    Observação:
        - A função filtra os eventos com base na data atual. Apenas os eventos com data maior ou igual à data atual serão exibidos.
    '''

    events = Event.objects.filter(date__gte=timezone.now())

    return render(
        request,
        'events/pages/events.html',
        context={
            'events': events,
            'is_admin': is_admin,
            'is_media_manager': is_media_manager,
            'is_authenticated': is_authenticated,
            'is_cordinator': is_coordinator
        }
    )


# Criar evento
@authenticated_user
def criar_evento(request,
                 is_authenticated,
                 is_admin,
                 is_media_manager,
                 is_devotion_manager,
                 is_coordinator,
                 is_umadjaf
                 ):
    '''
    Função para criar um novo evento no portal UMADJAF.

    Parâmetros:
        - request: A requisição HTTP recebida.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - Um objeto HttpResponse contendo a página HTML renderizada com o formulário de criação de evento.

    Observação:
        - A função verifica se o usuário está autenticado e se é um membro da
        equipe de mídia. Caso o usuário não esteja autenticado ou não seja um
        membro da equipe de mídia, ele será redirecionado para a página de
        eventos.
    '''

    if not is_authenticated:
        return redirect('events:eventos')

    if not (is_media_manager or is_admin or is_coordinator):
        return redirect('events:eventos')

    congregations = Congregations.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        theme = request.POST.get('theme')
        date = request.POST.get('date')
        hour = request.POST.get('hour')
        congregation_id = request.POST.get('congregation_id')
        logo = request.FILES.get('logo')
        background = request.FILES.get('background')

        event = Event(
            title=title,
            theme=theme,
            date=date,
            hours=hour,
            author_id=request.user.id,
            congregation=Congregations.objects.get(id=congregation_id)
        )

        if logo and background:
            event.logo = logo
            event.background = background

        if is_coordinator:
            event.is_general = False

        if is_media_manager or is_admin:
            event.is_general = True

        event.save()
        return redirect('events:eventos')  # Substitua 'alguma_url_para_listar_artigos' pela URL de destino

    return render(
        request,
        'events/pages/create_event.html',
        context={
            'congregations': congregations,
            'is_authenticated': is_authenticated,
            'is_admin': is_admin,
            'is_media_manager': is_media_manager,
            'is_coordinator': is_coordinator
        }
    )


# Gerenciar eventos
@authenticated_user
def eventos_manager(request,
                    is_authenticated,
                    is_admin,
                    is_media_manager,
                    is_devotion_manager,
                    is_coordinator,
                    is_umadjaf
                    ):
    '''
    Função para gerenciar os eventos do portal UMADJAF.

    Parâmetros:
        - request: A requisição HTTP recebida.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - Um objeto HttpResponse contendo a página HTML renderizada com a lista de eventos do portal UMADJAF.

    Observação:
        - A função verifica se o usuário está autenticado e se é um membro da
        equipe de mídia. Caso o usuário não esteja autenticado ou não seja um
        membro da equipe de mídia, ele será redirecionado para a página de
        eventos.
    '''

    if not is_authenticated:
        return redirect('events:eventos')

    if not (is_media_manager or is_admin):
        return redirect('events:eventos')

    calendar = Event.objects.all()

    return render(
        request,
        'events/pages/eventos_manager.html',
        context={
            'is_authenticated': is_authenticated,
            'is_admin': is_admin,
            'calendar_all': calendar
        }
    )


# Editar evento
@authenticated_user
def eventos_edit(request, calendar_id,
                 is_authenticated,
                 is_admin,
                 is_media_manager,
                 is_devotion_manager,
                 is_coordinator,
                 is_umadjaf
                 ):
    '''
    Função para editar um evento no portal UMADJAF.

    Parâmetros:
        - request: A requisição HTTP recebida.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - Um objeto HttpResponse contendo a página HTML renderizada com o formulário de edição de evento.

    Observação:
        - A função verifica se o usuário está autenticado e se é um membro da
        equipe de mídia. Caso o usuário não esteja autenticado ou não seja um
        membro da equipe de mídia, ele será redirecionado para a página de
        eventos.
    '''

    if not is_authenticated:
        return redirect('events:eventos')

    if not (is_media_manager or is_admin):
        return redirect('events:eventos')
    try:
        calendar = Event.objects.get(id=calendar_id)
    except Event.DoesNotExist:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    event_logo = calendar.logo
    event_background = calendar.background
    if request.method == 'POST':
        calendar_edit_form = CalendarForm(request.POST, request.FILES, instance=calendar)
        if calendar_edit_form.is_valid():
            # O objeto 'calendar' será atualizado com os dados do formulário
            calendar_edit_form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        calendar_edit_form = CalendarForm(instance=calendar)

    return render(
        request,
        'events/pages/partials/eventos_edit.html',
        context={
            'calendar_edit_form': calendar_edit_form,
            'calendar_id': calendar_id,
            'event_logo': event_logo,
            'event_background': event_background
        }
    )


# Deletar evento
@authenticated_user
def eventos_delete(request, calendar_id,
                   is_authenticated,
                   is_admin,
                   is_media_manager,
                   is_devotion_manager,
                   is_coordinator,
                   is_umadjaf
                   ):
    '''
    Função para deletar um evento no portal UMADJAF.

    Parâmetros:
        - request: A requisição HTTP recebida.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - Um objeto HttpResponseRedirect redirecionando para a página de eventos.

    Observação:
        - A função verifica se o usuário está autenticado e se é um membro da

events/resources/templates/events/pages/create_event.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    {% include "global/partials/head.html" %}
    {% block head %}
        <link rel="stylesheet" href="{% static 'events/css/events.css' %}">
        <title>Adicionar Evento</title>
    {% endblock head %}
    <style>
        {% comment %} #backgroundPreview {
            padding: 80px 0;
            position: relative;
            background-color: #d4d4d4;
            background-size: cover;
            background-position: left center;
            height: 20vh;
        } {% endcomment %}
    
    
        #title-calendar {
            width: 93%;
        }
    
        #theme-calendar {
            width: 93%;
        }

        
    </style>
</head>
<body>
    {% include 'global/partials/navbar.html' %}

    <div class="container mt-5">
        <div class="card">
            <div class="card-header text-center">
                <h1>ADICIONE O EVENTO</h1>
            </div>

            <!-- Preview do banner -->
            <div id="eventBanner" style="background-image: url('/media/events/default/bg.png')">
                <img id="eventLogo" src="/media/events/default/logo.png">
            </div>

            <!-- Formulário de criação de artigo -->
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="title" class="form-label">Título:</label>
                        <input type="text" class="form-control" id="title" name="title" required>
                    </div>
            
                    <div class="mb-3">
                        <label for="theme" class="form-label">Tema:</label>
                        <input type="text" class="form-control" id="theme" name="theme" required>
                    </div>
            
                    <div class="mb-3">
                        <label for="date" class="form-label">Data:</label>
                        <input type="date" class="form-control" id="date" name="date" required>
                    </div>
            
                    <div class="mb-3">
                        <label for="hour" class="form-label">Hora:</label>
                        <input type="time" class="form-control" id="hour" name="hour" required>
                    </div>
            
                    <div class="mb-3">
                        <label for="congregation_id" class="form-label">Congregação:</label>
                        <select class="form-select" id="congregation_id" name="congregation_id" required>
                            {% for congregation in congregations %}
                            <option value="{{ congregation.id }}">{{ congregation.name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" id="logo" name="logo" class="custom-file-input1" required>
                            <label class="custom-file-label" for="logo">Selecione o logo...</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" id="background" name="background" class="custom-file-input2" required>
                            <label class="custom-file-label" for="background">Selecione o background...</label>
                        </div>
                    </div>
            
                    {% comment %} <div class="mb-3">
                        <label for="logo" class="form-label">Logo:</label>
                        <input type="file" class="form-control" id="logo" name="logo">
                    </div> {% endcomment %}
            
                    {% comment %} <div class="mb-3">
                        <label for="background" class="form-label">Background:</label>
                        <input type="file" class="form-control" id="background" name="background">
                    </div> {% endcomment %}
            
                    <button type="submit" class="btn btn-primary">Criar Evento</button>
                </form>
            </div>
        </div>
    </div>
    <br>
    <br>

    {% include 'global/partials/footer.html' %}
    

    <!-- Inclua o JS do Quill -->
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    

    <!-- Script do preview -->
    <script>
        function readURL(input, previewElementId, isBackground = false) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                
                reader.onload = function (e) {
                    if (isBackground) {
                        document.getElementById(previewElementId).style.backgroundImage = 'url(' + e.target.result + ')';
                    } else {
                        var logoPreview = document.getElementById('eventLogo');
                        logoPreview.src = e.target.result;
                        logoPreview.style.display = 'block';
                    }
                }
                
                reader.readAsDataURL(input.files[0]);
            }
        }
        
        document.getElementById("logo").addEventListener("change", function(){
            readURL(this, "eventLogo");
        });
    
        document.getElementById("background").addEventListener("change", function(){
            readURL(this, "eventBanner", true);
        });
    </script>

    <!-- Script para exibir o nome do arquivo no input -->
    <script>
        document.querySelector('.custom-file-input1').addEventListener('change',function(e){
            var fileName = document.getElementById("logo").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        });
    </script>
    <script>
        document.querySelector('.custom-file-input2').addEventListener('change',function(e){
            var fileName = document.getElementById("background").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        });
    </script>
</body>
</html>

events/resources/templates/events/pages/eventos_manager.html
{% load static %}

<!DOCTYPE html>
<html>
    {% include "global/partials/head.html" %}
    {% block head %}
        <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <title>Lista de Eventos</title>
    {% endblock head %}
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }

        table, th, td {
            border: 1px solid black;
        }

        th, td {
            padding: 15px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:nth-child(odd) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #f2f2f2;
        }

        a {
            text-decoration: none;
            color: black;
        }

        a:hover {
            color: blue;
        }

        h1 {
            text-align: center;
            color: #fff;
        }

        .container {
            margin-top: 50px;
        }

        .btn {
            margin-top: 10px;
        }

        #user-table {
            width: 100%;
            border-collapse: collapse;
        }
    
        #user-table th, #congregation-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
    
        #user-table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #111111;
            color: white;
        }
    
        #user-table tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    
        #user-table tr:hover {
            background-color: #ddd;
        }

        .dataTables_wrapper {
            background-color: #fff; /* Altere para a cor de fundo desejada */
            margin-bottom: 0px;
        }

    </style>
<body>
    <!-- Barra de Navegação -->
    {% include 'global/partials/navbar.html' %}


    <div class="articles-container">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <h1 style="text-align: center; flex-grow: 1; margin-bottom: 23px;">Lista de Eventos</h1>
            <a href="{% url 'events:criar_evento' %}" class="btn btn-primary" style="margin-bottom: 25px;">Adicionar</a>

        </div>
    </div>

    <table id="user-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Evento</th>
                <th>Tema</th>
                <th>Data</th>
                <th>Local</th>
                <th>Menu</th>
            </tr>
        </thead>
        <tbody>
            {% for c in calendar_all %}
            <tr>
                <td>{{ c.id }}</td>
                <td>{{ c.title }}</td>
                <td>{{ c.theme }}</td>
                <td>{{ c.date }}</td>
                <td>{{ c.congregation }}</td>

                <td>
                    <a href="{% url 'events:eventos_edit' c.id %}" class="edit-link"><i class="fa fa-edit"></i></a>
                    <div class="modal fade" id="editModal-{{c.id}}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="editModalLabel">Editar Usuário</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div id="modal-body-{{c.id}}" class="modal-body">
                                <form id="edituser-{{c.id}}" method="POST" action="{% url 'events:eventos_edit' c.id %}">
                                    
                                </form>
                            </div>
                        </div>
                        </div>
                    </div>
                    <a href="{% url 'events:eventos_delete' c.id %}"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    

    <!-- Seção de Rodapé -->
    {% include 'global/partials/footer.html' %}

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function() {
            $('.add-link').click(function(e) {
                e.preventDefault();
                var url = $(this).attr('href');
                var userId = url.split('/').pop();
                $.get(url, function(data) {
                    $('#modal-body-add #add-calendar').html(data);
                    $('#addModal').modal('show');
                });
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            $('.edit-link').click(function(e) {
                e.preventDefault();
                var url = $(this).attr('href');
                var userId = url.split('/').pop();
                $.get(url, function(data) {
                    $('#modal-body-' + userId + ' #edituser-' + userId).html(data);
                    $('#editModal-' + userId).modal('show');
                });
            });
        });
    </script>
    <script>
        $(document).ready( function () {
            $('#user-table').DataTable({
                paging: true,
                ordering: true,
                info: true,
                pageLength: 20,  // Define o número inicial de itens por página
                lengthMenu: [[20, 40, 60, 100], [20, 40, 60, 100]]  // Define as opções de itens por página
            });
        });
    </script>
</body>
</html>

events/resources/templates/events/pages/events.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">

    {% include "global/partials/head.html" %}
    {% block head %}
        <link rel="stylesheet" href="{% static 'events/css/events.css' %}">
        <title>Eventos</title>
    {% endblock head %}

    <body>
        <!-- Barra de Navegação -->
        {% include 'global/partials/navbar.html' %}

        <!-- Banner de exibição do evento selecionado -->
        <section id="eventBanner_2" style="background-image: url('/media/events/default/bg.png')">
            <img id="eventLogo" src="/media/events/default/logo.png" alt="{{ next_event.title }}">
        </section>

        <!-- Lista dos próximos eventos -->
        <section id="calendar">
            {% for i in events %}
                <!-- Adicione um atributo 'data-banner-url' com a URL do banner do evento -->
                <div class="event" data-banner-url="{{ i.background.url }}" data-logo-url="{{ i.logo.url }}" onclick="changeBanner(this)">
                    <div class="event-title">{{ i.title }}: {{ i.theme }}</div>
                    <div class="event-detail">Data: {{ i.date }}</div>
                    <div class="event-detail">Hora: {{ i.hours }}</div>
                    <div class="event-detail">
                        Local: {{ i.congregation.name }} 
                        <a href="https://www.google.com.br/maps/place/{{ i.congregation.address|urlencode }}" target="_blank" class="google-maps-btn">
                            <i class="fas fa-map-marked-alt"></i> <!-- Alterado para um ícone de mapa e aumentado o tamanho -->
                        </a>
                    </div>
                </div>
            {% endfor %}
        </section>

        {% if is_admin or is_coordinator or is_media_manager %}
        <a id="float-btn" href="{% url 'events:criar_evento' %}" class="floating-btn">+</a>
        {% endif %}
        {% if is_admin or is_media_manager %}
        <a id="float-btn" href="{% url 'events:eventos_manager' %}" class="floating-btn2"><i class="fa fa-edit"></i></a>
        {% endif %}

        <!-- Seção de Rodapé -->
        {% include 'global/partials/footer.html' %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script>
            function changeBanner(eventElement) {
                // Obtém a URL do banner a partir do atributo de dados do evento clicado
                var bannerUrl = eventElement.getAttribute('data-banner-url');
                var logoUrl = eventElement.getAttribute('data-logo-url');
                
                // Certifica-se de que a URL do banner começa com '/media/'
                var correctedBannerUrl = bannerUrl;
                var correctedLogoUrl = logoUrl;
                
                // Atualiza o banner na parte superior da página
                document.getElementById('eventBanner_2').style.backgroundImage = 'url(' + correctedBannerUrl + ')';
                document.getElementById('eventLogo').src = correctedLogoUrl;
            }
        </script>
    </body>
</html>