home/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^c/add/?$', views.carrousel_add, name='carrousel_editor'),
    re_path(r'^c/?$', views.carrousel, name='carrousel'),
    re_path(r'^404/?$', views.does_not_exists, name='does_not_exists'),
    path('c/delete/<item_id>', views.carrousel_delete, name='carrousel_delete'),
]

portal_umadjaf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('', include('shop.urls')),
    path('', include('manager.urls')),
    path('', include('articles.urls')),
    path('', include('events.urls')),
    path('', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/forms.py
from django import forms  # type: ignore
from manager.models import Congregations
from .models import Event


# Formulário de calendário
class CalendarForm(forms.ModelForm):
    title = forms.CharField(
        label='Título',
        widget=forms.TextInput(attrs={
            'autocomplete': 'off',
            'id': 'title-calendar',
            'class': 'form-control'  # Adiciona a classe do Bootstrap
        })
    )
    date = forms.DateField(
        label='Data',
        widget=forms.DateInput(attrs={
            'type': 'date',
            'class': 'form-control'  # Adiciona a classe do Bootstrap
        })
    )
    theme = forms.CharField(
        label='Tema',
        widget=forms.TextInput(attrs={
            'autocomplete': 'off',
            'id': 'theme-calendar',
            'class': 'form-control'  # Adiciona a classe do Bootstrap
        })
    )
    is_general = forms.BooleanField(
        label='Geral',
        required=False
    )
    congregation = forms.ModelChoiceField(
        queryset=Congregations.objects.all(),
        empty_label='Selecione uma igreja',
        label='Congregação',
        widget=forms.Select(attrs={
            'class': 'form-select'  # Adiciona a classe do Bootstrap para selects
        })
    )
    logo = forms.ImageField(
        label='Logo',
        widget=forms.FileInput(attrs={
            'class': 'form-control'  # Adiciona a classe do Bootstrap para inputs de arquivo
        })
    )
    background = forms.ImageField(
        label='Background',
        widget=forms.FileInput(attrs={
            'class': 'form-control'  # Adiciona a classe do Bootstrap para inputs de arquivo
        })
    )

    class Meta:
        model = Event
        # Adicione aqui os campos que você deseja editar
        fields = ['title', 'date',
                  'theme', 'is_general', 'congregation', 'logo', 'background']

manager/resources/templates/manager/pages/calendar/partials/calendar_edit.html
<style>
    #backgroundPreview {
    padding: 80px 0;
    position: relative;
    background-color: #d4d4d4;
    background-size: cover;
    background-position: left center;
    height: 20vh;
}

#logoPreview {
    height: 80%;
    object-fit: cover;
    position: absolute;
    left: 30px;
    top: 50%;
    transform: translateY(-50%);
}

#title-calendar {
    width: 93%;
}

#theme-calendar {
    width: 93%;
}


</style>

<form method="post" enctype="multipart/form-data" action="{% url 'manager:calendar_edit' calendar_id %}">
    {% csrf_token %}
    {{ calendar_edit_form.as_p }}
    <br>
    <label for="id_logo">Preview:</label>
    <section id="backgroundPreview" style="background-image: url('/media/{{ event_background }}');">
        <img id="logoPreview" src="/media/{{ event_logo }}" alt="" style="display: block;">
    </section>
    <br>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<script>
    function readURL(input, previewElementId, isBackground = false) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                if (isBackground) {
                    document.getElementById(previewElementId).style.backgroundImage = 'url(' + e.target.result + ')';
                } else {
                    var logoPreview = document.getElementById('logoPreview');
                    logoPreview.src = e.target.result;
                    logoPreview.style.display = 'block';
                }
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    document.getElementById("id_logo").addEventListener("change", function(){
        readURL(this, "logoPreview");
    });

    document.getElementById("id_background").addEventListener("change", function(){
        readURL(this, "backgroundPreview", true);
    });
</script>