events/urls.py
from django.urls import path, re_path
from . import views

app_name = 'events'
urlpatterns = [

    re_path(r'^eventos/?$', views.eventos, name='eventos'),
    re_path(r'^eventos/criar/?$', views.criar_evento, name='criar_evento'),

    # Calendar manager
    path('eventos/manager/', views.eventos_manager, name='eventos_manager'),
    path('eventos/e/<int:calendar_id>', views.eventos_edit, name='eventos_edit'),
    path('eventos/d/<int:calendar_id>', views.eventos_delete, name='eventos_delete'),
]

gallery/urls.py
from django.urls import re_path, path
from . import views

app_name = 'gallery'
urlpatterns = [
    # Gallery
    re_path(
        r'^gallery/?$',
        views.gallery,
        name='gallery'
    ),
    # Gallery Add
    re_path(
        r'^gallery/add/?$',
        views.add_to_gallery,
        name='add_to_gallery'
    ),
    # Gallery Search
    re_path(
        r'^gallery/search/?$',
        views.search_gallery,
        name='search_gallery'
    ),
    # Gallery Manager
    re_path(
        r'^gallery/manager/?$',
        views.gallery_manager,
        name='gallery_manager'
    ),
    # Gallery Delete
    path(
        'gallery/manager/d/<int:photo_id>',
        views.gallery_photo_delete,
        name='gallery_photo_delete'
    ),


    # Gallery Marked User Manager
    re_path(
        r'^gallery/m/manager/?$',
        views.gallery_marked_user_manager,
        name='gallery_marked_user_manager'
    ),
    # Gallery Mark
    path(
        'gallery/m/<int:gallery_id>',
        views.mark_gallery,
        name='mark_gallery'
    ),
    # Gallery Unmark
    path(
        'gallery/u/<int:gallery_id>',
        views.unmark_gallery,
        name='unmark_gallery'
    ),
    # Gallery Marked
    path(
        'gallery/u/<int:gallery_id>/<int:user_id>',
        views.check_mark_gallery,
        name='check_mark_gallery'
    ),
]

home/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^c/add/?$', views.carrousel_add, name='carrousel_editor'),
    re_path(r'^c/?$', views.carrousel, name='carrousel'),
    re_path(r'^404/?$', views.does_not_exists, name='does_not_exists'),
    path('c/delete/<item_id>', views.carrousel_delete, name='carrousel_delete'),
]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'
urlpatterns = [

    # Users manager
    path('adm/users/', views.users, name='users'),
    path('adm/delete_user/<int:user_id>', views.delete_user, name='delete_user'),
    path('adm/user_edit/<int:user_id>', views.user_edit, name='user_edit'),
    path('adm/users/get', views.search_users, name='search_users'),

    # Roles manager
    path('adm/permissions/', views.users_roles, name='users_roles'),
    path('adm/permissions_changer/<int:user_id>', views.role_changer, name='permissions_changer'),

    # Congregation manager
    path('adm/congregations/', views.congregations, name='congregations'),
    path('adm/congregation_add/', views.congregation_add, name='congregation_add'),
    path('adm/congregation_edit/<int:congregation_id>', views.congregation_edit, name='congregation_edit'),
    path('adm/congregation_delete/<int:congregation_id>', views.congregation_delete, name='congregation_delete'),

    # Members manager
    path('adm/members/', views.members, name='members'),
    path('adm/member_positive/<int:member_id>', views.member_positive, name='member_positive'),
    path('adm/member_negative/<int:member_id>', views.member_negative, name='member_negative'),

]

portal_umadjaf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('', include('shop.urls')),
    path('', include('manager.urls')),
    path('', include('articles.urls')),
    path('', include('events.urls')),
    path('', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import re_path, path
from . import views

app_name = 'users'
urlpatterns = [
    # Login, register and profile
    re_path(r'^login/?$', views.login_, name='login'),
    re_path(r'^register/?$', views.register, name='register'),
    re_path(r'^my/?$', views.profile, name='profile'),
    re_path(
        r'^in/(?P<other_user_id>\d+)/?$',
        views.other_profile,
        name='other_profile'
        ),
    path('w/<other_user_id>/', views.redirect_whatsapp, name='redirect_whatsapp'),
    re_path(
        r'^in/notfound/?$',
        views.profile_does_not_exists,
        name='profile_does_not_exists'
        ),

    # Profile settings and logout
    path('settings/', views.profile_settings, name='settings'),
    path('logout/', views.profile_logout, name='logout'),
]

resources/templates/global/partials/footer.html
<footer>
    <style>
        /* Estilos para garantir que o rodapé fique na parte inferior da página */
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        
        footer {
            margin-top: auto;
            background-color: #f8f9fa; /* Cor de fundo do rodapé */
            color: #6c757d; /* Cor do texto do rodapé */
            text-align: center; /* Alinha o texto ao centro */
            padding: 6px 0 0 0; /* Espaçamento interno para dar altura ao rodapé */
            font-size: 0.9rem; /* Tamanho da fonte do texto do rodapé */
        }
    </style>

    <div class="footer-bottom">
        <p>&copy; 2024 ADJAF. Todos os direitos reservados.</p>
    </div>
</footer>

resources/templates/global/partials/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- favicon -->
    <link rel="icon" href="{% static 'ico.png' %}" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'global/partials/css/nav.css' %}"/>
    <link rel="stylesheet" href="{% static 'global/partials/css/footer.css' %}"/>
    <script src="{% static 'global/partials/js/head.js' %}"></script>
    {% block head %}{% endblock head %}
</head>

resources/templates/global/partials/navbar.html
{% load static %}

<header>
    <nav class="navbar">
        <a class="navbar-brand" href="{% url "home"%}">
            <img src="{% static 'ico.png' %}" alt="Logo" width="30" height="30" class="d-inline-block align-top">
        </a>
        <div class="" id="navbarNav">
            {% comment %} <a class="nav-link" href="{% url "store"%}">
                <i class="fa fa-store"></i><!-- Adiciona o ícone de notícias -->
            </a> {% endcomment %}
            <a class="nav-link" href="{% url 'gallery:gallery' %}">
                <i class="bi bi-image-fill"></i><!-- Adiciona o ícone de galeria -->
            </a>
            <a class="nav-link" href="{% url 'events:eventos' %}">
                <i class="bi bi-calendar-fill"></i><!-- Adiciona o ícone de eventos -->
            </a>
            <a class="nav-link" href="{% url 'articles:all_articles' %}">
                <i class="bi bi-book-fill"></i><!-- Adiciona o ícone de artigos -->
            </a>
            {% if is_admin %}
            <div class="dropdown">
                <a class="nav-link">
                    <i class="fas fa-user-shield"></i>
                </a>
                <div class="dropdown-content">
                    <a class="nav-link" href="{% url 'manager:users' %}">
                        <i class="fas fa-user-cog"></i> Usuários
                    </a>
                    <a class="nav-link" href="{% url 'manager:congregations' %}">
                        <i class="fas fa-church"></i> Igrejas
                    </a>
                    <a class="nav-link" href="{% url 'manager:members' %}">
                        <i class="fas fa-address-card"></i> Umadjaf
                    </a>
                    <a class="nav-link" href="{% url 'manager:users_roles' %}">
                        <i class="fas fa-key"></i> Equipe
                    </a>
                    <a class="nav-link" href="{% url 'events:eventos_manager' %}">
                        <i class="fa fa-calendar"></i> Eventos
                    </a>
                    <a class="nav-link" href="{% url 'articles:articles_manager' %}">
                        <i class="fa fa-italic"></i>  Devocionais
                    </a>
                    <a class="nav-link" href="{% url 'carrousel' %}">
                        <i class="fas fa-columns"></i> Carrosel
                    </a>
                </div>
            </div>
            {% endif %}
            <div class="dropdown">
                <a class="nav-link">
                    <i class="bi bi-person-fill"></i> <!-- Adiciona o ícone de perfil -->
                </a>
                <div class="dropdown-content">
                    {% if not is_authenticated %}
                    <a href="{% url "users:login" %}">Entrar</a>
                    <a href="{% url "users:register" %}">Cadastrar</a>
                    {% else %}
                    <a href="{% url "users:profile" %}">Perfil</a>
                    <a href="{% url "users:logout" %}">Sair</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>