articles/urls.py
from django.urls import path, re_path

from . import views

app_name = 'articles'
urlpatterns = [
    # Gereniar artigos
    re_path(r'^devocional/criar/?$', views.publish_articles, name='publish'),
    re_path(r'^devocional/one/(?P<article_id>\d+)/?$', views.article, name='article'),
    re_path(r'^devocional/?$', views.all_articles, name='all_articles'),
    re_path(r'^devocional/get?$', views.search_articles, name='search_articles'),

    # Articles manager
    path('devocional/manager/', views.articles_manager, name='articles_manager'),
    path('devocional/article_verify/<int:article_id>', views.article_verify, name='article_verify'),
    path('devocional/article_unverify/<int:article_id>', views.article_unverify, name='article_unverify'),
    path('devocional/article_delete/<int:article_id>', views.article_delete, name='article_delete'),

]

gallery/urls.py
from django.urls import re_path, path
from . import views

app_name = 'gallery'
urlpatterns = [
    # Gallery
    re_path(
        r'^gallery/?$',
        views.gallery,
        name='gallery'
    ),
    # Gallery Add
    re_path(
        r'^gallery/add/?$',
        views.add_to_gallery,
        name='add_to_gallery'
    ),
    # Gallery Search
    re_path(
        r'^gallery/search/?$',
        views.search_gallery,
        name='search_gallery'
    ),
    # Gallery Manager
    re_path(
        r'^gallery/manager/?$',
        views.gallery_manager,
        name='gallery_manager'
    ),
    # Gallery Delete
    path(
        'gallery/manager/d/<int:photo_id>',
        views.gallery_photo_delete,
        name='gallery_photo_delete'
    ),


    # Gallery Marked User Manager
    re_path(
        r'^gallery/m/manager/?$',
        views.gallery_marked_user_manager,
        name='gallery_marked_user_manager'
    ),
    # Gallery Mark
    path(
        'gallery/m/<int:gallery_id>',
        views.mark_gallery,
        name='mark_gallery'
    ),
    # Gallery Unmark
    path(
        'gallery/u/<int:gallery_id>',
        views.unmark_gallery,
        name='unmark_gallery'
    ),
    # Gallery Marked
    path(
        'gallery/u/<int:gallery_id>/<int:user_id>',
        views.check_mark_gallery,
        name='check_mark_gallery'
    ),
]

home/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^c/add/?$', views.carrousel_add, name='carrousel_editor'),
    re_path(r'^c/?$', views.carrousel, name='carrousel'),
    re_path(r'^404/?$', views.does_not_exists, name='does_not_exists'),
    path('c/delete/<item_id>', views.carrousel_delete, name='carrousel_delete'),
]

portal_umadjaf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('', include('shop.urls')),
    path('', include('manager.urls')),
    path('', include('articles.urls')),
    path('', include('events.urls')),
    path('', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import re_path, path
from . import views

app_name = 'users'
urlpatterns = [
    # Login, register and profile
    re_path(r'^login/?$', views.login_, name='login'),
    re_path(r'^register/?$', views.register, name='register'),
    re_path(r'^my/?$', views.profile, name='profile'),
    re_path(
        r'^in/(?P<other_user_id>\d+)/?$',
        views.other_profile,
        name='other_profile'
        ),
    path('w/<other_user_id>/', views.redirect_whatsapp, name='redirect_whatsapp'),
    re_path(
        r'^in/notfound/?$',
        views.profile_does_not_exists,
        name='profile_does_not_exists'
        ),

    # Profile settings and logout
    path('settings/', views.profile_settings, name='settings'),
    path('logout/', views.profile_logout, name='logout'),
]

gallery/models.py
from django.db import models
from users.models import User
import os
from PIL import Image
import io
from django.core.files.uploadedfile import InMemoryUploadedFile


# Upload das imagens para a pasta gallery
def upload_location(instance, filename):
    return f"gallery/{instance.event_date.strftime('%Y-%m-%d')}/{filename}"


# Recebe nome do autor o upload
def get_author_name(self):
    return User.objects.get(id=self.author_id).complete_name  # type: ignore


# Model para a galeria de fotos
class Gallery(models.Model):
    '''
    Model para a galeria de fotos

    Atributos:
    - event_id: ID do evento
    - event_date: Data do evento
    - uploaded_at: Data de upload
    - author_id: ID do autor
    - image: Imagem
    '''

    event_id = models.IntegerField(default=0)
    event_date = models.DateField()
    uploaded_at = models.DateTimeField(auto_now_add=True)
    author_id = models.IntegerField(default=0)
    image = models.ImageField(
        upload_to=upload_location,
        default='gallery/default.jpg'
        )

    # Deletar a imagem do disco ao deletar o objeto
    def delete(self, *args, **kwargs):
        if self.image:
            image_path = self.image.path
            if os.path.isfile(image_path):
                os.remove(image_path)
                image_dir = os.path.dirname(image_path)
                if not os.listdir(image_dir):
                    os.rmdir(image_dir)
        super(Gallery, self).delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        # Abrindo a imagem usando Pillow
        img = Image.open(self.image)
        max_size = 500 * 1024  # 500 KB
        quality = 75

        # Comprimir a imagem
        output = io.BytesIO()
        img.save(output, format='JPEG', quality=quality)
        while output.tell() > max_size and quality > 20:
            quality -= 5
            output.seek(0)
            img.save(output, format='JPEG', quality=quality)

        output.seek(0)

        # Alterar o ImageField para a imagem comprimida
        self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split('.')[0], 'image/jpeg', output.getbuffer().nbytes, None)
        super(Gallery, self).save(*args, **kwargs)

    def __str__(self):
        return f"({self.id}) Enviado em: {self.uploaded_at.strftime('%d/%m/%Y')}, Por: {get_author_name(self)}"


# Model para marcar a foto
class GalleryMarked(models.Model):
    '''
    Model para gerar o sistema de marcação da foto

    Atributos:
    - gallery: ID da galeria
    - marked_at: Data de marcação
    '''

    gallery = models.OneToOneField(Gallery, on_delete=models.CASCADE)
    marked_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"({self.id}) Gallery ID: {self.gallery.id}, Marked At: {self.marked_at.strftime('%d/%m/%Y')}"


# Model para marcar o usuário que marcou a foto
class GalleryMarkedUser(models.Model):
    '''
    Model para marcar o usuário que marcou a foto

    Atributos:
    - gallery_marked: ID da galeria marcada
    - marked_confirm: Confirmação de marcação
    - user_id: ID do usuário
    '''

    gallery_marked = models.ForeignKey(GalleryMarked, related_name='marked_users', on_delete=models.CASCADE)
    marked_confirm = models.BooleanField(default=False)
    user_id = models.IntegerField()

    def __str__(self):
        return f"({self.id}) GalleryMarked ID: {self.gallery_marked.id}, User ID: {self.user_id}"

gallery/views.py
from django.shortcuts import redirect, render
from utils.decorators import authenticated_user
from events.models import Event
from .models import Gallery, GalleryMarked, GalleryMarkedUser
from django.http import HttpResponseRedirect
from datetime import datetime
from django.core.paginator import Paginator


'''
É utilizado o decorator @authenticated_user para verificar se o usuário está
autenticado.

Ele entrega os seguintes parâmetros para as views:
    - is_authenticated: Indica se o usuário está autenticado.
    - is_admin: Indica se o usuário é um administrador.
    - is_media_manager: Indica se o usuário é um gerente de mídia.
    - is_devotion_manager: Indica se o usuário é um gerente de devoções.
    - is_coordinator: Indica se o usuário é um coordenador.
    - is_umadjaf: Indica se o usuário é um membro da UMADJAF.
'''


# Adicionar foto à galeria
@authenticated_user
def add_to_gallery(request,
                   is_authenticated,
                   is_admin,
                   is_media_manager,
                   is_devotion_manager,
                   is_coordinator,
                   is_umadjaf
                   ):
    '''
    Função para adicionar foto à galeria de fotos dos eventos

    Esta função adiciona uma foto à galeria de fotos dos eventos. A função
    renderiza a página de adição de fotos à galeria.

    Parâmetros:
        - request: Requisição HTTP.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - A página de adição de fotos à galeria.
    '''

    notification = False

    if not is_authenticated:
        return redirect('gallery:gallery')

    if not (is_media_manager or is_admin):
        return redirect('gallery:gallery')

    all_events = Event.objects.all().order_by('-id')

    if request.method == 'POST':
        event_id = request.POST.get('event_id')
        image = request.FILES.get('image')
        author_id = request.user.id

        if not Event.objects.filter(id=event_id).exists():
            event_date = request.POST.get('event_date')
            if event_date == '':
                notification = True
                return render(
                    request,
                    'gallery/pages/add_to_gallery.html',
                    context={
                        'is_authenticated': is_authenticated,
                        'is_admin': is_admin,
                        'is_media_manager': is_media_manager,
                        'all_events': all_events,
                        'notification': notification
                    }
                )
            event_date_ = datetime.strptime(event_date, '%Y-%m-%d')
        else:
            event_date_ = Event.objects.get(id=event_id).date

        if event_id == 0 or event_id == '0':
            event_id = int(''.join([i for i in event_date if i.isdigit()]))

        gallery = Gallery(
            event_id=event_id,
            event_date=event_date_,
            image=image,
            author_id=author_id
        )
        gallery.save()

        gallery_marked = GalleryMarked(gallery=gallery)
        gallery_marked.save()

        return redirect('gallery:add_to_gallery')

    return render(
        request,
        'gallery/pages/add_to_gallery.html',
        context={
            'is_authenticated': is_authenticated,
            'is_admin': is_admin,
            'is_media_manager': is_media_manager,
            'all_events': all_events,
            'notification': notification
        }
    )


# Galeria de fotos dos eventos
@authenticated_user
def gallery(request,
            is_authenticated,
            is_admin,
            is_media_manager,
            is_devotion_manager,
            is_coordinator,
            is_umadjaf):
    '''
    View para a página de galeria de fotos dos eventos

    Esta view renderiza a página de galeria de fotos dos eventos. A página
    exibe todas as fotos dos eventos cadastradas no sistema.

    Parâmetros:
        - request: Requisição HTTP.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - A página de galeria de fotos dos eventos.
    '''

    gallerie = Gallery.objects.all().order_by('-id')
    events = Event.objects.all().order_by('-id')
    user_id = request.user.id

    gallerie_paginator = Paginator(gallerie, 10)  # 8 artigos por página
    page_number = request.GET.get('page')  # Página atual
    page_gallerie = gallerie_paginator.get_page(page_number)
    user_id = request.user.id

    return render(
        request, 'gallery/pages/gallery.html',
        context={
            'is_authenticated': is_authenticated,
            'is_admin': is_admin,
            'is_media_manager': is_media_manager,
            'is_umadjaf': is_umadjaf,
            'user_id': user_id,
            'galleries': page_gallerie,
            'events': events
        }
    )


# Busca de fotos por evento
@authenticated_user
def search_gallery(request,
                   is_authenticated,
                   is_admin,
                   is_media_manager,
                   is_devotion_manager,
                   is_coordinator,
                   is_umadjaf
                   ):
    '''
    Função para buscar fotos por evento na galeria

    Esta função busca fotos por evento na galeria de fotos dos eventos. A
    função renderiza a página de galeria de fotos dos eventos com as fotos
    do evento selecionado.

    Parâmetros:
        - request: Requisição HTTP.
        - is_authenticated: Indica se o usuário está autenticado.
        - is_admin: Indica se o usuário é um administrador.
        - is_media_manager: Indica se o usuário é um gerente de mídia.
        - is_devotion_manager: Indica se o usuário é um gerente de devoções.
        - is_coordinator: Indica se o usuário é um coordenador.
        - is_umadjaf: Indica se o usuário é um membro da UMADJAF.

    Retorna:
        - A página de galeria de fotos dos eventos com as fotos do evento selecionado.
    '''

    gallerie = Gallery.objects.all().order_by('-id')
    events = Event.objects.all().order_by('-id')
    user_id = request.user.id

    search = request.GET.get('eventSelect')
    if search:
        print("Pesquisa: ", search)
        gallerie = Gallery.objects.filter(event_id=search).order_by('-id')

        if search == '0':
            gallerie = Gallery.objects.all().order_by('-id')
            for event in events:
                gallerie = gallerie.exclude(event_id=event.id)
    else:
        redirect('gallery:gallery')

    gallerie_paginator = Paginator(gallerie, 10)  # 8 artigos por página
    page_number = request.GET.get('page')  # Página atual
    page_gallerie = gallerie_paginator.get_page(page_number)
    user_id = request.user.id

    return render(
        request, 'gallery/pages/gallery.html',
        context={
            'is_authenticated': is_authenticated,
            'is_admin': is_admin,
            'is_media_manager': is_media_manager,
            'is_umadjaf': is_umadjaf,
            'user_id': user_id,
            'galleries': page_gallerie,
            'events': events
        }
    )


# Gerenciador de Galeria
@authenticated_user
def gallery_manager(request,
                    is_authenticated,
                    is_admin,
                    is_media_manager,
                    is_devotion_manager,
                    is_coordinator,
                    is_umadjaf
                    ):

    if not is_authenticated:
        return redirect('gallery:gallery')

    if not (is_media_manager or is_admin):
        return redirect('gallery:gallery')

    galleries = Gallery.objects.all().order_by('-id')

    return render(
        request, 'gallery/pages/manager_gallery.html',
        context={
            'is_authenticated': is_authenticated,
            'is_admin': is_admin,
            'is_media_manager': is_media_manager,
            'galleries': galleries
        }
    )


@authenticated_user
def gallery_photo_delete(request, photo_id,
                         is_authenticated,
                         is_admin,
                         is_media_manager,
                         is_devotion_manager,
                         is_coordinator,
                         is_umadjaf
                         ):

    if not is_authenticated:
        return redirect('gallery:gallery')

    if not (is_media_manager or is_admin):
        return redirect('gallery:gallery')

    gallery = Gallery.objects.get(id=photo_id)
    print(gallery)
    gallery.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


'''
As funções abaixo são utilizadas para gerenciar as marcações de fotos na
galeria de fotos dos eventos.

Os usuários podem solicitar a marcação de fotos na galeria de fotos dos
eventos. Os gerentes de mídia e administradores podem gerenciar as marcações
de fotos na galeria de fotos dos eventos.
'''


# Solicitar marcação de foto
@authenticated_user
def mark_gallery(request, gallery_id,
                 is_authenticated,
                 is_admin,
                 is_media_manager,
                 is_devotion_manager,
                 is_coordinator,
                 is_umadjaf
                 ):
    '''
    Função para solicitar marcação de foto na galeria

    Esta função solicita a marcação de uma foto na galeria de fotos dos

users/resources/templates/user_profile/pages/partials/gallery.html
{% load static %}

<style>
    .modal {
        display: none; /* Escondido por padrão */
        position: fixed; /* Fica fixo na tela */
        z-index: 1; /* Senta no topo */
        left: 0;
        top: 50px;
        width: 100%; /* Largura total */
        height: 100%; /* Altura total */
        overflow: auto; /* Habilita a rolagem se necessário */
        background-color: rgb(0,0,0); /* Cor de fundo */
        background-color: rgba(0,0,0,0.4); /* Cor de fundo com opacidade */
        padding-top: 220px; /* Espaçamento no topo */
    }
    
    /* Modal Content */
    .modal-header {
        position: absolute;
        top: 0;
        right: 0;
        border: none; /* Remove bordas */
    }

    .modal-button-top-right {
        border-radius: 50%; /* Borda arredondada no canto inferior esquerdo */
        height: 40px; /* Altura do botão */
        width: 40px; /* Largura do botão */
    }

    .modal-card {
        background-color: #fefefe;
        margin: 5% auto; /* Centraliza o modal */
        padding: 0px;
        width: 97%; /* Largura do modal */
        max-width: 800px; /* Máxima largura do modal */
        position: relative; /* Necessário para o botão no canto superior direito */
    }

    .modal-content {
        margin: auto;
        padding: 0px;
        width: 97%; /* Largura do conteúdo do modal */
        max-width: 800px; /* Máxima largura do conteúdo para não ficar muito grande em telas grandes */
    }

</style>


<div class="tab-pane fade" id="gallery">
    <div id="gallery" class="container-fluid">
        <div class="row justify-content-center mx-auto" style="width: auto;">
            <div class="profile-gallery">
                <div class="row row-profile-gallery">
                    {% for g in gallery %}
                        <div class="card gallery-profile">
                            <a onclick="selectPhoto(this, '{{ g.id }}')">
                                <img src="{{ g.gallery_marked.gallery.image.url }}" class="card-img-top gallery-image" alt="{{ g.gallery_marked.gallery.event_date }}">
                            </a>
                            <div id="photoModal-{{ g.id }}" class="modal">
                                <div class="modal-card">
                                    <img class="modal-content" id="selected-photo" src="{{ g.gallery_marked.gallery.image.url }}" >
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-12 d-flex justify-content-center align-items-center" style="color: white; font-weight: bold; font-size: 15px; height: 19vh;">
                            Nenhuma foto encontrada.
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        window.selectPhoto = function(eventElement, galleryId) {
            var modalId = "photoModal-" + galleryId; // Constrói o ID do modal com base no ID da galeria
            var modal = document.getElementById(modalId);
            var modalImg = document.getElementById("selected-photo" + galleryId);
            var eventNameElement = document.querySelector(".event_name"); // Seleciona o elemento do nome do evento
            var photoUrl = eventElement.getAttribute('data-photo-url');
            var eventTitle = eventElement.getAttribute('data-event-title');
    
            console.log("Event Title:", eventTitle); // Debugging: Verifica o valor de eventTitle
    
            modal.style.display = "block";
            modalImg.src = photoUrl;
            eventNameElement.innerHTML = eventTitle; // Atualiza o nome do evento
    
            var span = document.getElementsByClassName("close")[0];
    
            span.onclick = function() { 
                modal.style.display = "none";
            }
        }
    });
    
    window.onclick = function(event) {
        if (event.target.classList.contains('modal')) {
            event.target.style.display = "none";
        }
    }
</script>

users/resources/templates/user_profile/pages/partials/mocidade.html
{% load static %}
{% load member_profile %}

<div class="tab-pane fade" id="group-member">
    <div class="container-fluid">
        <div class="row justify-content-center mx-auto" style="width: auto;">
            {% for member in group_members %}
            <div class="card card-group-member">
                <img src="{% return_profile_picture member.id %}" class="img-group-member" alt="Profile Picture">
                <div class="details-group-member">
                    <div class="name-group-member">{{ member.complete_name }}</div>
                    <div class="bio-group-member">{% return_profile_bio member.id %}</div>
                </div>
                <a href="{% url 'users:other_profile' member.id %}" class="round-button">
                    <i class="fas fa-info-circle"></i>
                </a>
            </div>
            {% empty %}
            <div class="col-12 d-flex justify-content-center align-items-center" style="color: white; font-weight: bold; font-size: 15px; height: 20vh;">
                Nenhum membro encontrado.
            </div>
            {% endfor %}
        </div>
    </div>
</div>

users/resources/templates/user_profile/pages/partials/posts.html
{% load static%}
{% load versicles_api %}

<div class="tab-pane fade show active" id="pub">
    <div id="pub" class="container-fluid">
        <div class="row justify-content-center mx-auto" style="width: auto;">
            <div class="profile-posts">
                <div class="row row-profile-posts">
                    {% for post in posts %}
                        <div class="card pub-profile" style="position: relative;">
                            <div class="card-img-top pub-image-card" style="background-image: url('/media/{{ post.banner }}');" alt="{{ post.title }}"></div>
                            <div class="card-body pub-title">
                                <h5 class="card-title"><b>{{ post.title|truncatechars:30 }}</b></h5>
                                <blockquote class="blockquote">
                                    <p class="card-text"><i>{% fetch_versicle post.versicle %}</i></p>
                                </blockquote>
                            </div>
                            <div class="card-footer readmore">
                                <a href="{% url 'articles:article' post.id %}" class="btn btn-primary pub-btn">Leia mais</a>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-12 d-flex justify-content-center align-items-center" style="color: white; font-weight: bold; font-size: 15px; height: 20vh;">
                            Nenhum devocinal encontrado.
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<a id="float-btn" href="{% url 'articles:publish' %}" class="floating-btn">+</a>

users/resources/templates/user_profile/pages/partials/settings.html
{% load static %}

<div class="tab-pane fade" id="settings">
    <div id="settingsx" class="container">
        
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        var url = "{% url 'users:settings' %}";
    
        $.get(url, function(data) {
            $('#settingsx').html(data);
        });
    });
</script>
<script>
    $(document).ready(function() {
        $('#form_profile_picture').change(function() {
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#form_profile_picture_preview').attr('src', e.target.result);
            }
            reader.readAsDataURL(this.files[0]);
        });
    });
</script>